on:
  push:
    branches:
      - main
  pull_request:
jobs:
  job1:
    runs-on: ubuntu-latest
    name: Job
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - run: echo "$github"
        env:
          github: ${{ toJSON(github) }}
  job2:
    runs-on: ubuntu-latest
    name: Job
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - run: echo "$github"
        env:
          github: ${{ toJSON(github) }}
  job3:
    runs-on: ubuntu-latest
    name: Job
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - run: echo "$github"
        env:
          github: ${{ toJSON(github) }}
  job4:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I am a PR"
      - run: echo "I am run on the main branch with an update"
