on:
  push:
    branches:
      - main
  pull_request:
jobs:
  job1:
    runs-on: ubuntu-latest
    name: Job
    steps:
      - uses: actions/checkout@v4
      - run: echo "$github"
        env:
          github: ${{ toJSON(github) }}
  job2:
    runs-on: ubuntu-latest
    name: Job
    steps:
      - uses: actions/checkout@v4 
      - run: echo "$github"
        env:
          github: ${{ toJSON(github) }}
  job3:
    runs-on: ubuntu-latest
    name: Job
    steps:
      - uses: actions/checkout@v4
      - run: echo "$github"
        env:
          github: ${{ toJSON(github) }}
