on:
  push:
    branches:
      - main
  pull_request:
jobs:
  job1:
    runs-on: ubuntu-latest
    name: Job
    steps:
      - uses: actions/checkout@v4
      - run: sleep 1
  job2:
    runs-on: ubuntu-latest
    name: Job
    steps:
      - uses: actions/checkout@v4 
      - run: sleep 2
  job3:
    runs-on: ubuntu-latest
    name: Job
    steps:
      - uses: actions/checkout@v4
      - run: sleep 3